version: "3.7"

services:
  api:
    restart: always
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - "3333:3333"
    command: [sh, -c, "bun install && bun migrate && bun dev"]
    volumes:
      - ./:/app
    develop:
      watch:
        - action: rebuild
          path: .
  postgres:
    restart: always
    image: bitnami/postgresql:latest
    ports:
      - "5433:5432"
    environment:
      - POSTGRES_USER=docker
      - POSTGRES_PASSWORD=docker
      - POSTGRES_DB=pizzashop
    volumes:
      - postgres_data:/bitnami/postgresql

volumes:
  postgres_data:
